name: 'Snyk SCA scan and publish to Unify Platform'
description: 'Runs Snyk Software Composition Analysis scan to detect security vulnerabilities in open source dependencies and publishes to the Unify platform.'

inputs:
  cloudbees-url:
    description: Cloudbees API URL
    required: false
    default: "https://api.cloudbees.io"
  snyk-token:
    description: 'Snyk API token for authentication'
    required: true
  org-id:
    description: 'Snyk organization ID'
    required: true
  cli-params:
    description: 'Command line params for snyk open source scan'
    required: false
  build-directory:
    description: 'Build directory that holds the build tools'
    required: false
  ref:
    description: 'Flag to indicate the ref that should be archived (same as supplied to checkout).'
    required: false
    default: ''
  workspace-dir:
    description: 'Flag to mention the path where the checked out code will be present.'
    required: false
    default: ''
  step-id:
    description: 'The ID of the step in the workflow'
    required: false
    default: ''
outputs:
  critical-count:
    description: A string containing the number of Critical security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.critical-count}}
  very-high-count:
    description: A string containing the number of Very High security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.very-high-count}}
  high-count:
    description: A string containing the number of High security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.high-count}}
  medium-count:
    description: A string containing the number of Medium security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.medium-count}}
  low-count:
    description: A string containing the number of Low security findings discovered during the scan.
    value: ${{steps.process-outputs.outputs.low-count}}

runs:
  using: composite
  steps:

    - name: Create tar of source code
      shell: bash
      run: |
        tar -cvf output.tar .

    - name: Create request JSON file in workspace
      shell: bash
      run: |
        FILE_PATH="$GITHUB_WORKSPACE/store/request/request.json"
        mkdir -p "$(dirname "$FILE_PATH")"
        touch "$FILE_PATH"
        echo "File created at: $FILE_PATH"

    - name: Generate reference files
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e INPUT_CLOUDBEES_API_URL="${{ inputs.cloudbees-url }}" \
          -e INPUT_RUN_ID="${{ github.run_id }}" \
          -e INPUT_IS_GITHUB_WORKFLOW="true" \
          -e GITHUB_RUN_ID="${{ github.run_id }}" \
          -e GITHUB_WORKFLOW_REF="${{ github.workflow_ref }}" \
          -e GITHUB_RUN_ATTEMPT="${{ github.run_attempt }}" \
          -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
          -e GITHUB_REF_NAME="${{ github.ref_name }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_SERVER_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e GITHUB_JOB="${{ github.job }}" \
          -e GITHUB_PROVIDER="GITHUB" \
          -e GITHUB_WORKSPACE="${{ github.workspace }}" \
          -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
          -e GITHUB_OUTPUT="$GITHUB_OUTPUT" \
          -e GITHUB_ENV="$GITHUB_ENV" \
          -e ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN \
          -e ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL \
          public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:1f95fd45dd03fa6f363ff95cb20142fe4b7d83c4 \
          generate-references --asset-type "CODE"

    - name: Run SCC Scan for tag generation
      shell: bash
      run: |
        docker run --rm \
          -u root \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e RUN_ID="${{ github.run_id }}" \
          -e JOB_ID="${{ github.job }}" \
          -e STEP_ID="${{ inputs.step-id }}" \
          public.ecr.aws/l7o7z1g8/actions/assets-scc-scanner:9393ab805bb706c829c471e1dfc8e6ee73541253 \
          --mode single

    - name: Run Snyk SCA plugin
      shell: bash
      run: |
        docker run --rm \
          -u root \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e RUN_ID="${{ github.run_id }}" \
          -e JOB_ID="${{ github.job }}" \
          -e STEP_ID="${{ inputs.step-id }}" \
          -e SNYK_SCA_PROPS='{"accessToken": "${{ inputs.snyk-token }}", "orgName": "${{ inputs.org-id }}", "cliParams": "${{ inputs.cli-params }}", "buildDirectory": "${{ inputs.build-directory }}"}' \
          public.ecr.aws/l7o7z1g8/actions/assets-snyk-sca-scanner:80bea9113f19c64c9ff1d4c6a86c0519fbfebaab \
          --mode single


    - id: process-outputs
      name: Complete execution plan
      shell: bash
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          -e INPUT_CLOUDBEES_API_URL="${{ inputs.cloudbees-url }}" \
          -e INPUT_RUN_ID="${{ github.run_id }}" \
          -e INPUT_IS_GITHUB_WORKFLOW="true" \
          -e GITHUB_RUN_ID="${{ github.run_id }}" \
          -e GITHUB_WORKFLOW_REF="$GITHUB_WORKFLOW_REF" \
          -e GITHUB_RUN_ATTEMPT="${{ github.run_attempt }}" \
          -e GITHUB_RUN_NUMBER="${{ github.run_number }}" \
          -e GITHUB_REF_NAME="${{ github.ref_name }}" \
          -e GITHUB_REPOSITORY="${{ github.repository }}" \
          -e GITHUB_SERVER_URL="${{ github.server_url }}/${{ github.repository }}" \
          -e GITHUB_JOB="${{ github.job }}" \
          -e GITHUB_PROVIDER="GITHUB" \
          -e GITHUB_WORKSPACE="$GITHUB_WORKSPACE" \
          -e GITHUB_ENV="$GITHUB_ENV" \
          -v $GITHUB_OUTPUT:$GITHUB_OUTPUT \
          -e GITHUB_OUTPUT="$GITHUB_OUTPUT" \
          -e ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN \
          -e ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL \
          public.ecr.aws/l7o7z1g8/actions/assets-plugin-chain-utils:1f95fd45dd03fa6f363ff95cb20142fe4b7d83c4 \
          process-outputs


